version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./student_management_system:/code
    command: python manage.py runserver 127.0.0.1:8000
